import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import { ThemeProvider } from "@/contexts/ThemeContext";
// I18nProvider removed
import { NotificationProvider } from "@/contexts/NotificationContext";
import NotificationRenderer from "@/components/NotificationRenderer"; // Corrected import
import { AISuggestionProvider } from "@/contexts/AISuggestionContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { UndoRedoProvider } from "@/contexts/UndoRedoContext";
import { AccessibilityProvider } from "@/contexts/AccessibilityContext";
import { initializeTelemetry } from '@/lib/telemetry';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SmartAccessible CMS Toolkit",
  description: "Generated by Gemini",
};

import { OnboardingProvider } from '@/contexts/OnboardingContext';

(async () => {
  await initializeTelemetry();
})();

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <OnboardingProvider>
          <ThemeProvider>
            <NotificationProvider>
              <AuthProvider>
                <UndoRedoProvider>
                  <AISuggestionProvider>
                    <AccessibilityProvider>
                      <Layout>
                        {children}
                      </Layout>
                      <NotificationRenderer />
                    </AccessibilityProvider>
                  </AISuggestionProvider>
                </UndoRedoProvider>
              </AuthProvider>
            </NotificationProvider>
          </ThemeProvider>
        </OnboardingProvider>
      </body>
    </html>
  );
}