import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import { ThemeProvider } from "@/contexts/ThemeContext";
import I18nProvider from "@/contexts/I18nProvider";

import { NotificationProvider } from "@/contexts/NotificationContext";
import NotificationToast from "@/components/NotificationToast";
import { AISuggestionProvider } from "@/contexts/AISuggestionContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { UndoRedoProvider } from "@/contexts/UndoRedoContext";
import { AccessibilityProvider } from "@/contexts/AccessibilityContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SmartAccessible CMS Toolkit",
  description: "Generated by Gemini",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <svg style={{ display: 'none' }}>
          <filter id="protanopia">
            <feColorMatrix
              in="SourceGraphic"
              type="matrix"
              values="0.567 0.433 0 0 0
                      0.558 0.442 0 0 0
                      0 0.242 0.758 0 0
                      0 0 0 1 0"
            />
          </filter>
          <filter id="deuteranopia">
            <feColorMatrix
              in="SourceGraphic"
              type="matrix"
              values="0.625 0.375 0 0 0
                      0.7 0.3 0 0 0
                      0 0.3 0.7 0 0
                      0 0 0 1 0"
            />
          </filter>
          <filter id="tritanopia">
            <feColorMatrix
              in="SourceGraphic"
              type="matrix"
              values="0.95 0.05 0 0 0
                      0 0.433 0.567 0 0
                      0 0.475 0.525 0 0
                      0 0 0 1 0"
            />
          </filter>
          <filter id="achromatopsia">
            <feColorMatrix
              in="SourceGraphic"
              type="matrix"
              values="0.299 0.587 0.114 0 0
                      0.299 0.587 0.114 0 0
                      0.299 0.587 0.114 0 0
                      0 0 0 1 0"
            />
          </filter>
        </svg>
        <AccessibilityProvider>
          <AuthProvider>
            <I18nProvider>
              <ThemeProvider>
                <NotificationProvider>
                  <AISuggestionProvider>
                    <UndoRedoProvider>
                      <Layout>{children}</Layout>
                                            <NotificationRenderer /> {/* Replaced NotificationToast */}
                    </UndoRedoProvider>
                  </AISuggestionProvider>
                </NotificationProvider>
              </ThemeProvider>
            </I18nProvider>
          </AuthProvider>
        </AccessibilityProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}

     
      </body>
    </html>
  );
}

